customWorldBorder:
  enabled: true
  overworld: 10000
  nether: 7500
  end: 20000
lightGoldenAppleCraft:
  enabled: true
  goldUsed: 4
locatorBar:
  overworld: false
  nether: false
  end: true
enableNotchAppleCraft: false
pvp:
  overworld: true
  nether: true
  end: true
enableEnd: true
craftableCobwebs:
  enabled: true
  resultNumber: 2
allowEndCrystals: true
difficulty: #PEACEFUL, EASY, NORMAL, HARD
  overworld: HARD
  nether: HARD
  end: HARD
sleepPercentage: 100
anvilTweaks:
  enable: true
  disableTooExpensive: true
  costFactor: 1
endReplacements:
  elytraCraftingRecipe: false
  endStoneRecipe: false
  chorusFlowerRecipe: false
  spireTrimRecipe: false
netherite:
  lootBoost: false
  upgradeRecipe: true
  dupeRecipe:
    enabled: false
    useDiamondBlocks: false
  disableArmor: false
enchantmentMaxLevels:
  enabled: false
  protection: 3
  sharpness: 4
  power: 4
maceLimit:
  enabled: true
  count: 2
autoRestock: false
turtleTweaks:
  cheaperTurtleMaster: true
  dropScutes: false
  scuteChance: 35
speed:
  enabled: false #determines if speed overrides will be applied
  happyGhast: 0.1025
disableElytraMovementCheck: true