name: PiglysUtilityTweaks
version: '1.4.2'
main: dev.Pigly3.piglysUtilityTweaks.PiglysUtilityTweaks
description: A plugin to add tweaks useful for small SMPs.
author: Pigly3
api-version: '1.21.11'
permissions:
  putils.operator:
    default: op